const PIPE_DRIVER_DEFAULT_FILL_COLOR = 'white';
const PIPE_DRIVER_SELECTABLE_FILL_COLOR = 'lightgray';
const PIPE_DRIVER_SELECTED_COLOR = 'gray';
const PIPE_DRIVER_OUTLINE_COLOR = 'black';
const PIPE_DRIVER_DIAMETER_IN_METERS = 0.1;
const PIPE_DRIVER_THICKNESS_IN_METERS = 0.01;

const PIPE_DRIVER_PIPE_THICKNESS_IN_METERS = 0.01;
const PIPE_DRIVER_PIPE_COLOR = 'black';

const PIPE_DRIVER_ADDITIONAL_OFFSET_METERS = 0.15;